hilgi/hilgi/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

hilgi/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    # User management
    path('accounts/', include('allauth.urls')),

    # Local apps
    path('', include('obstsorten.urls')),
    path('wiese/', include('wiese.urls')),
    #path('hofladen/', include('hofladen.urls'))
]

wiese/urls.py
from django.urls import path
from .views import (
        WieseCreateView,
        WieseDeleteView,
        WieseListView,
        WieseView,
        WieseUpdateView,
        BaumView,
        BaumPicView,
        BluehWiesenListView,
        BluehWiesenView,
        Set_dynamic_static_view,
)

app_name = 'wiese'

urlpatterns = [
    path('', WieseListView.as_view(), name='wiesen-list'),
    path('<int:wid>/', WieseView.as_view(), name='wiesen-detail'),
    path('create/', WieseCreateView.as_view(), name='wiesen-create'),
    path('update/<int:id>/', WieseUpdateView.as_view(), name='wiesen-update'),
    path('delete/<int:id>/', WieseDeleteView.as_view(), name='wiesen-delete'),
    path('baum/<int:id>/', BaumView.as_view(), name='baum-detail'),
    path('baumpic/<path:pic>/<int:id>/', BaumPicView.as_view(), name='baumpic'),
    path('wiese_dynamic/<str:val>/', Set_dynamic_static_view, name='set_dyn_static'),

    path('bluehwiesen/', BluehWiesenListView.as_view(), name='bluehwiesen'),
    path('bluehwiesen/<int:id>', BluehWiesenView.as_view(), name='bluehwiese'),
]

wiese/models.py
from django.db import models
from django.contrib.postgres.fields import ArrayField

class Entwicklungsziele(models.Model):
    id            = models.IntegerField(primary_key=True)
    ziel          = models.CharField(max_length=256, blank=True, null=True)

class PflegeMassnahme(models.Model):
    id            = models.IntegerField(primary_key=True)
    datum         = models.DateTimeField(null=True, blank=True)
    wer           = models.CharField(max_length=64, blank=True, null=True)
    bezeichnung   = models.CharField(max_length=2048, blank=True, null=True)
    erledigt      = models.BooleanField(default=False)

class Baumarten(models.Model):
    name          = models.CharField(max_length=64, blank=True, null=True)
    www           = ArrayField(models.URLField(max_length=256, blank=True),
                                 size=5, null=True)

class Blumen(models.Model):
    name          = models.CharField(max_length=64, blank=True, null=True)
    www           = ArrayField(models.URLField(max_length=256, blank=True),
                                 size=5, null=True)

class Graeser(models.Model):
    name          = models.CharField(max_length=64, blank=True, null=True)
    www           = ArrayField(models.URLField(max_length=256, blank=True),
                                 size=5, null=True)

class Kraeuter(models.Model):
    name          = models.CharField(max_length=64, blank=True, null=True)
    www           = ArrayField(models.URLField(max_length=256, blank=True),
                                 size=5, null=True)

class Wiese(models.Model):
    wiesen_id     = models.IntegerField(primary_key=True)
    name          = models.CharField(max_length=64)
    obstwiese     = models.BooleanField(default=True)
    bluehwiese    = models.BooleanField(default=False)
    www_name      = models.CharField(max_length=128, blank=True, null=True)

    #
    # Flur Daten
    #
    biotop_nr     = models.IntegerField(blank=True, null=True)
    flur_nr       = models.IntegerField(blank=True, null=True)
    groesse       = models.IntegerField(blank=True, null=True)
    eigentuemer   = models.CharField(max_length=64, blank=True, null=True)
    lage          = models.CharField(max_length=256, blank=True, null=True)

    #
    # Bestandsdaten
    #
    standort      = models.CharField(max_length=256, blank=True, null=True)
    ogestalt      = models.CharField(max_length=256, blank=True, null=True)
    angr_nutzung  = models.CharField(max_length=256, blank=True, null=True)
    beschreibung  = models.CharField(max_length=256, blank=True, null=True)
    bes_planzen_tiere = models.CharField(max_length=256, blank=True, null=True)

    #
    # Entwicklungsziele
    #
    ziel_beschreibung  = models.ManyToManyField(Entwicklungsziele,
                                     related_name='wiese_ziele')

    #
    # Massnahmen
    #
    sicherungs_massnahmen  = models.CharField(max_length=256, blank=True, null=True)
    pflege_massnahmen_plan = models.ManyToManyField(PflegeMassnahme,
                                     related_name='plan_massnahme')

    pflege_massnahmen_ist = models.ManyToManyField(PflegeMassnahme,
                                     related_name='ist_massnahme')

    #
    # sonstiges
    #
    pate  = models.CharField(max_length=64, blank=True, null=True)
    zufahrt  = models.BooleanField(default=True)
    foerderung_moeglich = models.BooleanField(default=False)
    foerderung_beantragt = models.BooleanField(default=False)
    gepflegt_durch = models.CharField(max_length=64, blank=True, null=True)


    anmerkungen = models.CharField(max_length=1024, blank=True, null=True)
    letzte_pflege = models.DateTimeField(null=True, blank=True)

    #
    # Bewuchs
    #
    baeume = models.ManyToManyField(Baumarten, related_name='wiese_baum')
    blumen = models.ManyToManyField(Blumen, related_name='wiese_blume')
    graeser = models.ManyToManyField(Graeser, related_name='wiese_gras')
    kraeuter = models.ManyToManyField(Kraeuter, related_name='wiese_kraut')

    def __str__(self):
        return self.www_name

wiese/forms.py
from django import forms

from wiese.models import Wiese

class WieseModelForm(forms.ModelForm):
    class Meta:
        model = Wiese
        fields = [
            'wiesen_id',
            'name',
            'obstwiese',
            'bluehwiese',
        ]

class WiesenUpdateForm(forms.ModelForm):
    class Meta:
        model = Wiese
        fields = [
            'name',
            'obstwiese',
            'bluehwiese',
        ]

wiese/views.py
import os
from os.path import join, exists, isdir
from pprint import pformat

from django.shortcuts import render, get_object_or_404, redirect, reverse
from django.views.generic import TemplateView, ListView
from django_tables2 import SingleTableView, SingleTableMixin
from django.views import View

from .forms import WieseModelForm, WiesenUpdateForm
from obstsorten.models import Wiese, ObstBaum, ObstSorten
from obstsorten.defs import Obst_Type
from obstsorten.views import ObstLinkIn
from wiese.tables import WiesenTable
from wiese.wiese import WiesenLeaflet, BluewiesenLeaflet
from baeume.baeume import BaumLeaflet
from hilgi.utils import BaumSessionClass

from init_db import  Streuobst_geo, Bluehwiesen_geo

DEBUG = int(os.environ.get('DEBUG', default=1))

APP = 'wiese'

class WieseObjectMixin(ObstLinkIn, object):
    model = Wiese
    def get_object(self, wiesen_id=None):
        obj = None
        if wiesen_id is not None:
            obj = get_object_or_404(self.model, wiesen_id=wiesen_id)
        return obj

    def set_dynamic(self, context):
        if not 'baeume_statisch' in self.request.session:
            context['baeume_statisch'] = ''
            context['baeume_dynamisch'] = "disabled"
        else:
            context['baeume_statisch'] = self.request.session['baeume_statisch']
            context['baeume_dynamisch'] = self.request.session['baeume_dynamisch']

class WieseCreateView(View):
    template_name = "wiese/wiese_create.html"
    def get(self, request, *args, **kwargs):
        # GET method
        form = WieseModelForm()
        context = {"form": form}
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        # POST method
        form = WieseModelForm(request.POST, request.FILES or None)

        if DEBUG:
            print("request.FILES: %s" % pformat(request.FILES))
        if form.is_valid():
            form.save()
            form = WieseModelForm()
        context = {"form": form}
        return render(request, self.template_name, context)

class WieseListView(WieseObjectMixin, SingleTableMixin, ListView):
    #
    # Darstellung aller Obst-Wiesen mit Karte und Liste der definierten Wiesen
    #
    model = Wiese
    table_class = WiesenTable
    template_name = "wiese/wiese_list.html"

    def get_context_data(self, **kwargs):
        """
            Holt die ContextDaten vom Model und der WiesenTabelle
            wird hier noch mal um die dynamischen geo_objects
            und um die Menu-Entry erweitert
        """
        context = super().get_context_data(**kwargs)
        baeume = BaumLeaflet()
        wiesen = WiesenLeaflet(geo_json_file=Streuobst_geo, verbose=DEBUG)
        #bluehwiesen = WiesenLeaflet(geo_json_file=Bluehwiesen_geo, verbose=DEBUG)
        #print("WieseListView: dir: %s" % pformat(dir(self)))

        self.set_dynamic(context)

        #
        # Die beiden Parameter baeume und wiesen werden im JavaScript
        # verwendet
        #
        context["baeume"] = baeume.get_all_geo_objects()
        context["wiesen"] = wiesen.get_geo_objects()
#        context["bluehwiesen"] = bluehwiesen.get_geo_objects()

        context['grafik'] ='images/wiese/Hilgh_StreuobstWiesen_2020_09.png'
        context['obstsorten_menu'] = self.get_Obst_menu()
        context['wiesen_list'] = Wiese.objects.all().order_by('name')

        return context

class BluehWiesenListView(WieseObjectMixin, SingleTableMixin, ListView):
    #
    # Darstellung aller BlühWiesen mit Karte und Liste der definierten Wiesen
    #
    model = Wiese
    table_class = WiesenTable
    template_name = "wiese/bluehwiesen.html"

    def get_context_data(self, **kwargs):
        """
            Holt die ContextDaten vom Model und der WiesenTabelle
            wird hier noch mal um die dynamischen geo_objects
            und um die Menu-Entry erweitert
        """
        context = super().get_context_data(**kwargs)
        bluehwiesen = BluewiesenLeaflet(geo_json_file=Bluehwiesen_geo, verbose=DEBUG)
        bluehwiesen.add_wiesen_pics()

        self.set_dynamic(context)

        #
        # Die beiden Parameter baeume und wiesen werden im JavaScript
        # verwendet
        #
        context["bluehwiesen"] = bluehwiesen.get_geo_objects()

        context['grafik'] ='images/wiese/Hilgh_StreuobstWiesen_2020_09.png'
        return context

class WieseView(WieseObjectMixin, View):
    """
        Zeig eine Wiesen Grafik und
        deren darauf stehenden Bäume in einer darunter aufgeführten Liste
        die Liste enthält die Baum-Nr. mit einem URL-Link zum BaumView

    """
    template_name = "wiese/wiese_detail.html" # DetailView
    def __find_grafik__(self, wid):
        """
            such die zur wiesen_id zugehörige Grafik in dem Static Verzeichnis
        """
        pwd = os.getcwd()
        for f in os.listdir(join(pwd, 'static', 'images', APP)):
            if f.find("%s_" % wid) == 0 and \
               'png' in f.lower():
                return join('images', APP, f)
        return "NOT FOUND"

    def __find_trees__(self, wid):
        """
            Suche alle Bäume der Wiese, die sollen unterhalb des Bildes
            aufgelistet werden
        """
        trees = ObstBaum.objects.filter(wiese=wid).order_by('baum_id')
        ptrees = []
        for tree in trees:
            ptree = {
                'baum_id' : tree.baum_id,
                'name' : ObstSorten.objects.get(sorten_id=tree.sorten_id_id).obst_sorte,
                'zustand' : tree.zustand,
                'letzter_schnitt' : tree.letzter_schnitt,
                }
            #
            # Die '99' Nummer sind unbestimmte Bäume da fügen wird keine
            # URL ein
            #
            #if '99' not in "%s" % tree.sorten_id_id:
            ptree['url'] = tree.sorten_id_id
            ptrees.append(ptree)

        return ptrees

    def __get_geo_json_info__(self, wid):
        """
            Hol die GEO-JSON Info für die Wiese
        """
        geo_wiesen = WiesenLeaflet(geo_json_file=Streuobst_geo)
        wiese = Wiese.objects.get(wiesen_id=wid)
        geo_info = geo_wiesen.get_geo_info4wiese(wiese.www_name)

        #print("get_geo_json_info: %s" % pformat(geo_info))

        # In dem GEO-JSON vom GIS steckt ein MultiPolygon
        # wir können hier aber nur ein Polygon brauchen!
        #
        # zu allem Übel sind die Longitude und latitude Werte in dem
        # GEO-Json in der falschen Reihenfolge, also drehen wir die hier
        geo = []
        for point in geo_info['geometry']['coordinates'][0][0]:
            geo.append([point[1], point[0]])

        return geo

    def get(self, request, wid=None, *args, **kwargs):
        # GET method
        baeume = BaumLeaflet()
        context = {
            'object'          : self.get_object(wiesen_id=wid),
            'grafik'          : self.__find_grafik__(wid),
            'trees'           : self.__find_trees__(wid),
            'wiesen_list'     : Wiese.objects.all().order_by('name'),
            'obstsorten_list' : ObstSorten.objects.all().order_by('sorten_id'),
            'obstsorten_menu' : self.get_Obst_menu(),
            'baeume'          : baeume.get_all_trees4wiese(wid),
            'wiese_geo_info'  : self.__get_geo_json_info__(wid),
        }
        #print("Wiese-Detail: get <%s>" % pformat(baeume.geo_layers))
        self.set_dynamic(context)
        return render(request, self.template_name, context)

class BaumView(WieseObjectMixin, View):
    """
        Zeig alle Infos zu einem Baum
          - SortenInfos
          - Bilder
          - BaumInfos
    """
    template_name = "wiese/baum_detail.html" # BaumView
    def __find_pics__(self, baum, wiesen_name):
        """
            such die zur baum_id zugehörigen Bilder in dem Static Verzeichnis
            gib diese als Liste zurück
        """
        baum_pics = []
        baum_i = 0
        pwd = os.getcwd()
        bdir = join(pwd, 'static', 'images', 'baum')
        if not exists(bdir):
            if DEBUG:
                print("Could not find: %s" % bdir)
            return []

        for f in os.listdir(join(pwd, 'static', 'images', 'baum')):
            if isdir(join(pwd, 'static', 'images', 'baum', f)) and \
                    f == wiesen_name:
                for b in os.listdir(join(pwd, 'static', 'images', 'baum', f)):
                    if b.find("%s_" % baum.baum_id) == 0:
                        #baum_pics.append(join('images', 'baum', f, b))
                        #
                        # Generier eine List von Dicts damit wir in der
                        # Darstellung ein Carousel mit Buttons bauen können
                        #    siehe: baum_detail.html
                        #
                        baum_pics.append(
                                { 'nr'  : baum_i,
                                  'pic' : join('images', 'baum', f, b),
                                })
                        baum_i += 1

            elif f.find("%s_" % baum.baum_id) == 0:
                baum_pics.append(join('images', 'baum', f))
        return baum_pics

    def __find_trees__(self, wid):
        """
            Suche alle Bäume der Wiese, die sollen unterhalb des Bildes
            aufgelistet werden
        """
        trees = ObstBaum.objects.filter(wiese=wid).order_by('baum_id')
        ptrees = []
        for tree in trees:
            ptree = {
                'baum_id' : tree.baum_id,
                'name' : ObstSorten.objects.get(sorten_id=tree.sorten_id_id).obst_sorte,
                'zustand' : tree.zustand,
                'letzter_schnitt' : tree.letzter_schnitt,
                }
            #
            # Die '99' Nummer sind unbestimmte Bäume da fügen wird keine
            # URL ein
            #
            if '99' not in "%s" % tree.sorten_id_id:
                ptree['url'] = tree.sorten_id_id
            ptrees.append(ptree)

        return ptrees

wiese/templates/wiese/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Uwe W. Schäfer">

    <title>{% block title %}Wiesen-Verwaltung{% endblock title %}</title>

    <!-- Bootstrap Core CSS -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

  <!-- LeafLet  -->
  <link rel="stylesheet" href="{% static 'css/leaflet.css' %}" />
  <script src="{% static 'js/leaflet.js' %}"></script>
  <link rel="stylesheet" href="{% static 'leaflet-plugins/leaflet-markercluster/MarkerCluster.css' %}"/>
  <link rel="stylesheet" href="{% static 'leaflet-plugins/leaflet-markercluster/MarkerCluster.Default.css' %}"/>
  <script src="{% static 'leaflet-plugins/leaflet-markercluster/MarkerCluster.js' %}">    </script>

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  
  <link rel="stylesheet" href="{% static 'hilgi_map.css' %}">
  
  <script src="{% static 'js/BaumPopUp.js' %}">    </script>
 
</head>
<body>

{% if user.is_authenticated %}
    <div class="navbar">
        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>                        
                </button>
                <ul class="nav navbar-nav">
                    <li>
                        <a class="navbar-brand" href="https://www.hilgertshausen-tandern.de/">
                            <img class="rounded-circle" src="{% static 'images/Hilgertshausen_Wappen.jpg' %}" height=27 border=5px>
                        </a>
                    </li>
                    <li>
                        <a class="navbar-brand" href="https://www.hilgertshausen-tandern.de/"> Hilgertshausen</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-header -->
            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <i id="nav_blue" class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-user">
			    <li>
				<a class="nav navbar-brand" href="/obstsorten">Obstsorten</a>
			    </li>
			    <li>
				<a href="{% url 'obstbaeume' %}" class="nav navbar-brand">  Obstbäume</a>
			    </li>
        {% if user.is_staff %}
                            <li>
                                <a class="p-2 text-dark" href="/">Gruppen Seite</a>
                            </li>
        {% endif %}
                            <li>
                                <a href="{% url 'account_logout' %}"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                            </li>
                            <li role="presentation" class="divider"></li>
                            <li>
                                <a class="p-2 text-dark" href="{% url 'about' %}">Kontakt</a>
                            </li>
                        </ul>
                        <!-- /.dropdown-user -->
                    </li>
                    <!-- /.dropdown -->
                </ul>
            </div>
        </nav>
    </div>
    <!-- /.navbar-top-links -->
    <div class="row">
        <div class="col-sm-2">
           <nav>
                    <div class="navbar-default sidebar" role="navigation">
                        <div class="sidebar-nav navbar-collapse collapse in">
                            <ul class="nav" id="side-menu">
                                <li>
                                    <a href="{% url 'wiese:wiesen-list' %}"><i class="fa fa-dashboard fa-fw"></i>     Überblick</a>
                                </li>
                                {% if wiesen_list %}
                                <li>
                                    <a href="#">
                                        <i class="fa fa-eye fa-fw"></i>
                                           Obstwiesen
                                        <i class="fa fa-caret-down"></i>
                                    </a>
                                    <ul class="nav nav-second-level">
                                        {% for instance in wiesen_list %}
                                            <li>
                                                <a href="{% url 'wiese:wiesen-detail' instance.wiesen_id %}">
                                                {{ instance.www_name }}
                                                </a>
                                            </li>
                                        {% endfor %}
                                    </ul>
                                    <!-- /.nav-second-level -->
                                </li>
                                {% endif %}
                                {% if obstsorten_menu %}
                                <li>
                                    <a href="{% url 'obstsorten' %}"><i class="fa fa-eye fa-fw"></i>    Obstsorten
                                        <i class="fa fa-caret-down"></i>
                                    </a>
                                    <ul class="nav nav-second-level">
                                    {% for otype in obstsorten_menu %}
                                        <li>
                                            <a href="#"><i class="fa fa-eye fa-fw"></i>
                                                {{ otype.name }}
                                                <i class="fa fa-caret-down"></i>
                                            </a>
                                            <ul class="nav nav-second-level">
                                                {% for o in otype.obstsorten %}
                                                    <li>
                                                        <a href="{% url 'obstsorten_detail' o %}"> {{ o }} </a>
                                                    </li>
                                                {% endfor %}
                                            </ul>
                                        </li>
                                    {% endfor %}
                                    </ul>
                                </li>
                                {% else %}
                                <li>
                                    <a href="{% url 'obstsorten' %}"><i class="fa fa-eye fa-fw"></i>  Obstsorten</a>
                                </li>
                                {% endif %}
                            </ul>
                        </div>
                        <!-- /.sidebar-collapse -->
                    </div>
            <!-- /.navbar-static-side -->
           </nav>
        </div>
        <div class="col-sm-9">
              {% block content %}{% endblock %}
        </div>

    </div>
   
    <!-- Metis Menu Plugin JavaScript -->
    <script src="{% static 'vendor/metisMenu/metisMenu.min.js' %}"></script>

    <!-- Custom Theme JavaScript -->
    <script src="{% static 'js/sb-admin-2.js' %}"></script>
{% else %}
    <div class="row">
	<div class="d-flex flex-column flex-md-row align-items-center">
        <center>
            <p><h1>Streuobstwiesen der Gemeinde Hilgertshausen</h1></p>
	    <img class="mainpic" src="{% static 'images/Hilgertshausen_Wappen.jpg' %}" width=200>
        </center>
        <p><br></p>
    <!-- Der folgende Block ist nur für die BaumInfo OHNE Login -->
    <!-- In dem Fall steht derjenige vor dem Baum und hat keine Kennung -->
    {% if baum_infos.baum_id %}
       
        <div class="col-sm-9">
              {% block baum_content %}{% endblock %}
        </div>
        <!-- Metis Menu Plugin JavaScript -->
        <script src="{% static 'vendor/metisMenu/metisMenu.min.js' %}"></script>

        <!-- Custom Theme JavaScript -->
        <script src="{% static 'js/sb-admin-2.js' %}"></script>
    {% else %}
	</div>
        <div class="col-mg-12">
            <div class="panel panel-primary">
                <div class="panel-heading text-center">
                    <strong>Sie sind nicht angemeldet.</strong>
                </div>
                <div class="panel-body text-center">
                    Zur Verwendung dieser WWW-Seite benötigen Sie eine Kennung.
                    Diese erhalten Sie bei der Gemeinde Hilgertshausen-Tandern.
		    <h3><a href="{% url 'account_login' %}">Log In</a></h3>
		</div>
            </div>
        </div>
    {% endif %}
    </div>
{% endif %}
 
{% block script %} {% endblock %}

</body>

</html>

wiese/templates/wiese/baum_pic.html
{% extends 'wiese/base.html' %}
{% load static %}

{% block content %}
<h1>{{baum_infos.baum_id }} - {{ sorte.obst_sorte }}</h1>
<p>
    {% if baum_pic %}
        <img class="baumpic" src="{% static baum_pic %}">
    {% else %}
        Keine Grafik vorhanden
    {% endif %}

</p> 
{% endblock %}

wiese/templates/wiese/bluehwiesen.html
{% extends 'wiese/blueh_base.html' %}
{% load static %}

{% block title %}Blühwiesen{% endblock title %}

{% block content %}

<div class="container">
    <div class="row">
        <h2> In 2021 neu angelegte Blühwiesen</h2>
      
        <!-- Dynamische Präsentation der Bäume mit Laeflet -->
        {{ bluehwiesen|json_script:"bluehwiesen-data" }}

        <div id="map"></div>

        <p id="WiesenInfo">
            Auf der obigen Map sind die in Hilgertshausen im Jahre 2021
            neu angelegten bzw. angesäten Blühfläschen durch rote Polygone
            gekennzeichnet.
        </p>
        <p>
            Ein Klick auf ein Polygon öffnet ein Popup-Fenster,
            in dem ein Bild der Wiese und deren Arbeitsname ersichtlich wird.
            Durch einen Klick auf das dargestellte Bild wird eine 
            WWW-Seite geöffnet, auf der weitere Bilder der Wiese und zusätzliche
            Informationen zu den verwendeten Blumensamen und Zeitpunkten 
            eingesehen werden können.
        </p>
    </div>
</div>

{% block script %}
  <script src="{% static 'js/bluehwiese_map.js' %}"></script>
{% endblock script %}

{% endblock content %}

wiese/templates/wiese/wiese_create.html
{% extends '_base.html' %}

{% block content %}


<form enctype="multipart/form-data" action='.' method='POST'>{% csrf_token %}
    {{ form.as_p }}
    <input type='submit' value='save' />
</form>

{% endblock %}

wiese/templates/wiese/wiese_detail.html
{% extends 'wiese/base.html' %}
{% load static %}

{% block content %}
<div class="row">
    <div class="col-xs-9">
        <h2>{{object.wiesen_id }} - {{ object.www_name }}</h2>
    </div>
    <div class="col-xs-3">
        <button type="button" class="btn btn-info" id='getLocation' onclick=getLocation()>Find Me</button>
    </div>

    <!-- Dynamische Präsentation der Bäume mit Laeflet -->
    {{ baeume|json_script:"sorten-layer" }}
    {{ obst_icon|json_script:"obst-icons" }}
    {{ wiese_geo_info|json_script:"wiese-geo-data" }}

    <div id="map"></div>

<!--
    {% if object.obstwiese %}
	<p>Die Wiese ist eine Obstwiese</p>
    {% endif %}
   
    {% if object.bluehwiese %}
	<p>Diese Wiese ist eine Blühwiese</p>
    {% endif %}
-->
    <div class="panel-body">
	<table width="100%" class="table table-striped table-bordered table-hover" id="baum-liste">
	    <thead>
		<tr>
		    <th>Baum Nr.</th>
		    <th>Bezeichnung</th>
		    <th>Zustand</th>
		    <th>letzter Schnitt</th>
		    <th>Düngung nötig</th>
		    <th>letzte Düngung</th>
		</tr>
	    </thead>
	    <tbody>
		{% for instance in trees %}
		    <tr>
			<th><button type="button" class="btn btn-default">
			    {% if instance.url %}
				<a href="{% url 'wiese:baum-detail' instance.baum_id %}">
			      {{ instance.baum_id }}
                </a>
			    {% else %}
			      {{ instance.baum_id }}
			    {% endif %}
			    </button></th>
			<th>
			    {% if instance.url %}
                    <a href="{% url 'wiese:baum-detail' instance.baum_id %}">
                    {{ instance.name }}
                    </a>
			    {% else %}
                    {{ instance.name }}
			    {% endif %}
            </th>
			<th>{{ instance.zustand }}</th>
			<th>{{ instance.letzter_schnitt }}</th>
			<th>{{ instance.duengung_noetig }}</th>
			<th>{{ instance.letzte_duengung }}</th>
		    </tr>
		{% endfor %}
	    </tbody>
	</table>
    </div>
</div>

{% block script %}
  <script src="{% static 'js/wiese_details.js' %}"></script>
{% endblock script %}

{% endblock content %}