hilgi/hilgi/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

hilgi/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    # User management
    path('accounts/', include('allauth.urls')),

    # Local apps
    path('', include('obstsorten.urls')),
    path('wiese/', include('wiese.urls')),
    #path('hofladen/', include('hofladen.urls'))
]

hofladen/urls.py
from django.urls import path

from .views import HofladenView

app_name = 'hofladen'

urlpatterns = [
	path('bio-view/<int:bio>/<int:sid>/', HofladenView.as_view(), name='bio-view'),
	path('bio-view/<int:bio>', HofladenView.as_view(), name='bio-view'),
	path('unverp-view/<int:unverpackt>', HofladenView.as_view(), name='unverp-view'),
	path('hofladen-view/<int:rid>/', HofladenView.as_view(), name='hofladen-view'),
	path('hofladen-view/<int:rid>/<int:uid>/', HofladenView.as_view(), name='hofladen-view'),
	path('', HofladenView.as_view(), name='hofladen-view'),
]

obstsorten/urls.py
from django.urls import path

from .views import (
    HomePageView,
    AboutPageView,
    ObstSortenView,
    ObstSortenDetView,
    BaumInfosView,
)


urlpatterns = [
    path('about/', AboutPageView.as_view(), name='about'), 
    path('', HomePageView.as_view(), name='home'),
    path('obstsorten', ObstSortenView.as_view(), name='obstsorten'),
    path('baeume', BaumInfosView.as_view(), name='obstbaeume'),
    path('obstsorten_detail/<str:sorte>/', ObstSortenDetView.as_view(), name='obstsorten_detail'),
]

wiese/urls.py
from django.urls import path
from .views import (
        WieseCreateView,
        WieseDeleteView,
        WieseListView,
        WieseView,
        WieseUpdateView,
        BaumView,
        BaumPicView,
        BluehWiesenListView,
        BluehWiesenView,
        Set_dynamic_static_view,
)

app_name = 'wiese'

urlpatterns = [
    path('', WieseListView.as_view(), name='wiesen-list'),
    path('<int:wid>/', WieseView.as_view(), name='wiesen-detail'),
    path('create/', WieseCreateView.as_view(), name='wiesen-create'),
    path('update/<int:id>/', WieseUpdateView.as_view(), name='wiesen-update'),
    path('delete/<int:id>/', WieseDeleteView.as_view(), name='wiesen-delete'),
    path('baum/<int:id>/', BaumView.as_view(), name='baum-detail'),
    path('baumpic/<path:pic>/<int:id>/', BaumPicView.as_view(), name='baumpic'),
    path('wiese_dynamic/<str:val>/', Set_dynamic_static_view, name='set_dyn_static'),

    path('bluehwiesen/', BluehWiesenListView.as_view(), name='bluehwiesen'),
    path('bluehwiesen/<int:id>', BluehWiesenView.as_view(), name='bluehwiese'),
]

hilgi/obstsorten/models.py
from django.contrib.postgres.fields import ArrayField
from django.db import models

class ObstSorten(models.Model):
    obst_type       = models.TextChoices('Obst_Type', 'Apfel, Birne, Kirche, Zwetschge, Nuss, Quitte, Mispel, unbekannt')
    obst_sorte      = models.CharField(max_length=64)
    reifezeit       = models.CharField(max_length=30)
    verwendung      = models.CharField(max_length=248)
    geschmack       = models.CharField(max_length=248)
    lagerfaehigkeit = models.CharField(max_length=248)
    alergie_info    = models.CharField(max_length=248)
    www             = ArrayField(models.CharField(max_length=128, blank=True),
                                 size=5)
    bilder          = ArrayField(models.ImageField(upload_to='uploads/Sorte'),
                                 blank=True, size=20)

class Wiese(models.Model):
    wiesen_id     = models.AutoField(primary_key=True)
    name          = models.CharField(max_length=30)
    bilder        = ArrayField(models.ImageField(upload_to='uploads/Wiese'),
                                 blank=True, size=20)
    grafik        = models.ImageField(upload_to='uploads/Wiese', default=None)
    obstwiese     = models.BooleanField(default=True)
    bluehwiese    = models.BooleanField(default=False)

class ObstBaum(models.Model):
    baum_id     = models.AutoField(primary_key=True)
    obst_sorte  = models.ForeignKey(ObstSorten, on_delete=models.CASCADE)
    wiese       = models.ForeignKey(Wiese, on_delete=models.CASCADE)
    bilder      = ArrayField(models.ImageField(upload_to='uploads/Wiese'),
                                 blank=True, size=20)
    

obstsorten/models.py
from django.contrib.postgres.fields import ArrayField
from django.db import models

class ObstTypen(models.Model):
    id  = models.AutoField(primary_key=True)
    name = models.CharField(max_length=64, blank=False)

class ObstSorten(models.Model):
    sorten_id       = models.IntegerField(primary_key=True)
    obst_type       = models.IntegerField()
    type_name       = models.ForeignKey(ObstTypen, on_delete=models.CASCADE)
    obst_sorte      = models.CharField(max_length=64,
        help_text='Obstsorte: Name der Obstsorte. z.B. rheinischer Winterrambour', null=True)
    pflueck_reif    = models.CharField(max_length=1024, blank=True, null=True)
    genuss_reif     = models.CharField(max_length=1024, blank=True, null=True)
    verwendung      = models.CharField(max_length=1024, null=True)
    geschmack       = models.CharField(max_length=1024, null=True)
    lagerfaehigkeit = models.CharField(max_length=1024, null=True)
    alergie_info    = models.CharField(max_length=1024, null=True)
    www             = ArrayField(models.URLField(max_length=256, blank=True),
                                 size=5, null=True)

    def __str__(self):
        return self.obst_sorte

class Wiese(models.Model):
    wiesen_id     = models.IntegerField(primary_key=True)
    name          = models.CharField(max_length=64)
    obstwiese     = models.BooleanField(default=True)
    bluehwiese    = models.BooleanField(default=False)
    www_name      = models.CharField(max_length=128, blank=True, null=True)

    def __str__(self):
        return self.www_name

class ObstBaum(models.Model):
    baum_id     = models.AutoField(primary_key=True)
    sorten_id   = models.ForeignKey(ObstSorten, on_delete=models.CASCADE)
    wiese       = models.ForeignKey(Wiese, on_delete=models.CASCADE)
    zustand     = models.CharField(max_length=248, blank=True)
    letzter_schnitt = models.DateField(null=True, blank=True)
    letzte_duengung = models.DateField(null=True, blank=True)
    duengung_noetig = models.BooleanField(default=False)
    coordinate = models.CharField(max_length=24, blank=True, null=True)

    def __str__(self):
        try:
            return "%s_%s" % (self.baum_id, self.sorten_id.obst_sorte)
        except:
            return "%s" % self.baum_id

obstsorten/views.py
import os
from os.path import join
from django.shortcuts import render

# Create your views here.
from django.views.generic import TemplateView
from django_filters.views import FilterView
from django_tables2 import SingleTableView, SingleTableMixin
from django_tables2.config import RequestConfig
from django_tables2.export.export import TableExport
from django_tables2.export.views import ExportMixin

from obstsorten.models import Wiese, ObstBaum, ObstSorten
from obstsorten.defs import Obst_Type
from baeume.baeume import BaumLeaflet
from baeume.tables import BaumInfosTable
from baeume.filters import BaumInfosFilter

DEBUG = int(os.environ.get('DEBUG'))

APP = 'obstsorten'

class HomePageView(TemplateView):
    template_name = 'home.html'


class AboutPageView(TemplateView):
    template_name = 'about.html'

    def get(self, request, *args, **kwargs):
        from hilgi import Version, Datum
        context = { 'VERSION' : Version,
                    'DATUM'   : Datum,
                  }
        return render(request, self.template_name, context)

class ObstLinkIn(object):
    obst = ObstSorten.objects.all().order_by('obst_sorte')

    def get_Obst_menu(self):
        """
            generier ein zwei-dimensionales Dictionary mit
            Obstsorten-Type : ObstSorte
        """
        obst_menu = []
        obst_sorten_menu = {}
        for os in self.obst:
            otype = Obst_Type[os.obst_type]
            if otype.lower() == 'unbekannt' or \
               otype.lower() == 'tod':
                continue
            elif not otype in obst_sorten_menu:
                obst_sorten_menu[otype] = [os.obst_sorte]
            else:
                obst_sorten_menu[otype].append(os.obst_sorte)
        for o in sorted(obst_sorten_menu.keys()):
            os = {
                    'name': o,
                    'obstsorten' : obst_sorten_menu[o],
                 }
            obst_menu.append(os)
        return obst_menu

class ObstSortenView(ObstLinkIn, TemplateView):
    template_name = 'obstsorten.html'

    def __find_grafik__(self, oid):
        """
            such die zur Obstsorte zugehörige Grafik in dem Static Verzeichnis
        """
        pwd = os.getcwd()
        for f in os.listdir(join(pwd, 'static', 'images', APP)):
            if f.find("%s_" % oid) == 0:
                #print("OBST-BILD gefunden %s" % f)
                return join('images', APP, f)

    def get_queryset(self):
        # obst = ObstSorten.objects.all().order_by('sorten_id')
        robst = []
        for oid in range(0,len(Obst_Type)):
            # hol immer nur die Obstsorten für den Type
            if Obst_Type[oid] == 'unbekannt' or \
                    Obst_Type[oid] == 'Tod':
                        continue
            obst = ObstSorten.objects.filter(obst_type=oid).order_by('obst_sorte')
            for o in obst:
                if 'unbestimmt' in o.obst_sorte:
                    continue
                sorte = {
                    'obst_type' : Obst_Type[o.obst_type],
                    'obst_sorte' : o.obst_sorte,
                    'pflueck_reif' : o.pflueck_reif,
                    'verwendung' : o.verwendung,
                    'geschmack' : o.geschmack,
                    'lagerfaehigkeit' : o.lagerfaehigkeit,
                    'alergie_info' : o.alergie_info,
                    'www' : o.www,
                    'picture' : self.__find_grafik__(o.sorten_id),
                    }
                robst.append(sorte)
        return robst

    def get(self, request, sid=None, *args, **kwargs):
        # GET method
        context = {'object': self.get_queryset(),
                   'wiesen_list' : Wiese.objects.all().order_by('wiesen_id'),
                   'obstsorten_list' : ObstSorten.objects.all().order_by('sorten_id'),
                   'obstsorten_menu' : self.get_Obst_menu(),
                  }
        return render(request, self.template_name, context)

class ObstSortenDetView(ObstLinkIn, TemplateView):
    template_name = 'obstsorten_detail.html'

    def __find_grafik__(self, oid):
        """
            such die zur Obstsorte zugehörige Grafik in dem Static Verzeichnis
        """
        pwd = os.getcwd()
        for f in os.listdir(join(pwd, 'static', 'images', APP)):
            if f.find("%s_" % oid) == 0:
                #print("OBST-BILD gefunden %s" % f)
                return join('images', APP, f)

    def get_queryset(self):
        o = ObstSorten.objects.get(obst_sorte=self.kwargs.get('sorte'))
        sorte = {
            'obst_type'       : Obst_Type[o.obst_type],
            'obst_sorte'      : o.obst_sorte,
            'pflueck_reif'    : o.pflueck_reif,
            'verwendung'      : o.verwendung,
            'geschmack'       : o.geschmack,
            'lagerfaehigkeit' : o.lagerfaehigkeit,
            'alergie_info'    : o.alergie_info,
            'www'             : o.www,
            'picture'         : self.__find_grafik__(o.sorten_id),
            'sorten_id'       : o.sorten_id,
            }
        return sorte

    def find_wiesen(self, sorten_id):
        """
            hole alle Wiesen auf der diese Obst-Sorte wächst
            hierzu müssen wir zunächst alle Bäume vom Type finden
            in deren Elementen sind die Wiesen-Ids enthalten
        """
        wiesen = {}
        for baum in ObstBaum.objects.filter(sorten_id=sorten_id):
            wiese = Wiese.objects.get(wiesen_id=baum.wiese_id)
            if wiese.name not in wiesen:
                wiesen[wiese.www_name] = wiese.wiesen_id
        return wiesen



    def get(self, request, sid=None, *args, **kwargs):
        # GET method
        ob = self.get_queryset()
        baeume = BaumLeaflet()

        context = {'object': ob,
                   'wiesen_sorte'    : self.find_wiesen(ob['sorten_id']),
                   'wiesen_list'     : Wiese.objects.all().order_by('wiesen_id'),
                   'obstsorten_list' : ObstSorten.objects.all().order_by('sorten_id'),
                   'baeume'          : baeume.get_geo_objects4sorte(ob['sorten_id']),
                   'obstsorten_menu' : self.get_Obst_menu(),
                  }
        return render(request, self.template_name, context)

class BaumInfosView(ObstLinkIn, SingleTableMixin, FilterView):

    model = ObstBaum
    table_class = BaumInfosTable
    filterset_class = BaumInfosFilter
    template_name = "baum_infos.html"

templates/_base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}Wiesen-Verwaltung{% endblock title %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/base.css' %}">

  <!-- Bootstrap Core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- MetisMenu CSS -->
    <link href="{% static 'vendor/metisMenu/metisMenu.min.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
    <link href="{% static 'css/sb-admin-2.css' %}" rel="stylesheet">

    <!-- Morris Charts CSS -->

    <!-- jQuery -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
  
</head>
<body>
  <header>
    <!-- Fixed navbar -->
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4\
     mb-3 bg-white border-bottom shadow-sm">
      <a href="{% url 'wiese:wiesen-list' %}" class="navbar-brand my-0 mr-md-auto font-weight-normal">Streuobstwiesen</a>
      <a href="{% url 'wiese:bluehwiesen' %}" class="navbar-brand my-0 mr-md-auto font-weight-normal">Blühwiesen</a>

      <nav class="my-2 my-md-0 mr-md-3">
        <a class="p-2 text-dark" href="{% url 'about' %}">About</a>
        {% if user.is_authenticated %}
          <a class="p-2 text-dark" href="{% url 'account_logout' %}">Log Out</a>
        {% else %}
          <a class="p-2 text-dark" href="{% url 'account_login' %}">Log In</a>
	  <!-- <a class="btn btn-outline-primary" href="{% url 'account_signup' %}">Sign Up</a> -->
        {% endif %}
      </nav>
    </div>
  </header>
  <div class="container">
    {% block content %}
    {% endblock content %}
  </div>
  <!-- JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

templates/about.html
{% extends 'base.html' %}
{% load static %}

{% block title %}About{% endblock title %}

{% block content %}
<h1>About Page</h1>

<h1>WWW-Seite der Nachhaltigkeitsgruppe Hilgertshausen</h1>
<h3>Darstellung der Streuobstwiesen der Gemeinde Hilgertshausen:</h3>
<h4>Version: {{VERSION}} vom {{ DATUM }}</h4>

<p>
Diese WWW-Seite soll die Streuobst- und Blühwiesen der Gemeinde Hilgertshausen-Tandern
Ortsteil Hilgertshausen, sowie nachhaltige Einkaufsmöglichkeiten rund um die Gemeinde, abbilden.
</p>
<p>
    Wir verfolgen mit dieser WWW-Seite keinen wirtschaftlichen Zweck,
    sondern möchten die Umwelt und die Nachhaltigkeitsbestrebungen
    in unserer Gemeinde und dem Umkreis fördern.
</p>
<p>
Die gezeigten Darstellungen können durchaus Fehler beinhalten.
Der Verfasser übernimmt keine Garantie auf die Korrektkeit der dargestellten
Informationen. Insbesondere die Hinweise zur Allergie-Verträglichkeit sind
nur ein Hinweis. Es besteht kein Anspruch auf Fehlerfreiheit!
</p>

<p>
Die WWW-Seite wurde von der Schäfer &amp; Tobies Software u. Consulting GmbH erstellt
</p>


<h1>Kontakt</h1>
<table id="contact">
<tbody>
    <th width="40%"></th> <th width="60%"></th>
    <tr>
	<td colspan="2">
	    <h3>Sie erreichen uns unter:</h3>
	</td>
    </tr>
    <tr>
	<th>Postadresse:</th>
	    <td><strong>SCH&Auml;FER &amp; TOBIES</strong></td>
    </tr>
    <tr>
	<th>&nbsp;</th>
	<td>Software und Consulting GmbH</td>
    </tr>
    <tr>
	<th>&nbsp;</th>
	<td>Herbststra&szlig;e 12</td>
    </tr>
    <tr>
	<th>&nbsp;</th>
	<td>86567 Hilgertshausen</td>
    </tr>
    <tr>
	<td colspan="2"><br /></td>
    </tr>
    <tr>
	<th>Telefon:</th>
	<td>0 82 50-9 29 03</td>
    </tr>
    <tr>
	<th>Fax:</th>
	<td>0 82 50-9 29 05</td>
    </tr>
    <tr>
	<td colspan="2"><br /></td>
    </tr>
    <tr>
	<th>e-mail:</th>
	<td><a href="mailto:info@schaefer-tobies.de">info@schaefer-tobies.de</a></td>
    </tr>
    <tr>
	<th>Homepage:</th>
	<td><a href="http://www.schaefer-tobies.de">www.schaefer-tobies.de</a></td>
    </tr>
    <tr>
	<th> Datenschutzerkl&auml;rung</th>
	<td><a href='https://www.schaefer-tobies.de/privacy/'>  Datenschutz</a></td>
    </tr>
    <tr>
	<td colspan="2"> Weitere Angaben nach &sect;6 TDG: </td>
    </tr>
    <tr>
	<th>Vertretungsberechtigter:</th>
	<td>Uwe. W. Sch&auml;fer (Gesch&auml;ftsf&uuml;hrer)</td>
    </tr>
    <tr>
	<th>e-mail:</th>
	<td><a href="mailto:uws@schaefer-tobies.de">uws@schaefer-tobies.de</a></td>
    </tr>
    <tr>
	<th>Handelsregistereintrag:</th>
	<td>HRB 100 958 - M&uuml;nchen</td>
    </tr>
    <tr>
	<th>USt-IdNr.:</th>
	<td>DE154496129</td>
    </tr>
</tbody>
</table>

{% endblock content %}

templates/base.html
../wiese/templates/wiese/base.html

templates/baum_infos.html
{% extends 'base.html' %}
{% load django_tables2 %}
{% load bootstrap4 %}
{% load static %}

{% block title %}Obstbäume{% endblock title %}

{% block content %}
{% if filter %}
    <form action="" method="get" class="form form-inline">
        {% bootstrap_form filter.form layout='inline' %}
        {% bootstrap_button 'filter' %}
    </form>
{% endif %}
    {% render_table table %}
{% endblock content %}

templates/geo_base.html
{% load static %}
<!DOCTYPE html>
<html lang="de">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="Uwe W. Schäfer">

  <title>
    {% block title %}
      Hofläden rund um Hilgertshausen
    {% endblock title %}
  </title>

<!-- Bootstrap Core  -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

  <!-- LeafLet  -->
  <link rel="stylesheet" href="{% static 'css/leaflet.css' %}" />
  <script src="{% static 'js/leaflet.js' %}"></script>
  <link rel="stylesheet" href="{% static 'leaflet-plugins/leaflet-markercluster/MarkerCluster.css' %}"/>
  <link rel="stylesheet" href="{% static 'leaflet-plugins/leaflet-markercluster/MarkerCluster.Default.css' %}"/>
  <script src="{% static 'leaflet-plugins/leaflet-markercluster/MarkerCluster.js' %}">    </script>

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

 <link rel="stylesheet" href="{% static 'hilgi_map.css' %}">

  <style>
   
  </style>
</head>
<body>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <ul class="nav navbar-nav">
          <a class="navbar-brand" href="https://www.hilgertshausen-tandern.de/">
            <img class="rounded-circle" src="{% static 'images/Hilgertshausen_Wappen.jpg' %}" height=27 border=5px>
          </a>
          <li>
            <a class="navbar-brand" href="https://www.hilgertshausen-tandern.de/"> Hilgertshausen</a>
          </li>
      </ul>
    </div>
    <!-- /.navbar-header -->
    <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav navbar-right">
            <li>
              <a id="nav_blue" class="navbar-brand" href="/wiese/" >
                Streuobstwiesen
              </a>
            </li>
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    <i id="nav_blue" class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
                </a>
                <ul class="dropdown-menu">
                    <li>
                         <a class="p-2 text-dark" href="{% url 'about' %}">Kontakt</a>
                    </li>
                  {% if user.is_staff %}
                    <li>
                         <a class="p-2 text-dark" href="/">Gruppen Seite</a>
                    </li>
                  {% endif %}
                </ul>
                <!-- /.dropdown-user -->
            </li>
            <!-- /.dropdown -->
        </ul>
        <!-- /.navbar-top-links -->
      </div>
    </div>
</nav>

<div class="row">
  <div class="col-sm-2">
    <nav>
      <div class="navbar-default sidebar" role="navigation">
        <div class="sidebar-nav navbar-collapse collapse in">
            <ul class="nav" id="side-menu">
              <li>
                 <a href="{% url 'hofladen:hofladen-view' %}"><i class="fa fa-dashboard fa-fw"></i>
                Alle Verkaufsstellen</a>
              </li>
              <li>
                  <a href="{% url 'hofladen:bio-view' 1 %}">Bio Produkte</a>
              </li>
              <li>
                  <a href="#"><i class="fa fa-eye fa-fw"></i> 
                      Bio Siegel
                      <i class="fa fa-caret-down"></i>
                  </a>
                  <ul class="nav nav-second-level">
                      {% for o in OekoSiegel %}
                        <li>
                          <a href="{% url 'hofladen:bio-view' 1 o.id%}"> {{ o.name }} </a>
                        </li>
                      {% endfor %}
                  </ul>
              </li>
              <li>
                  <a href="#"><i class="fa fa-eye fa-fw"></i> 
                      Rubriken
                      <i class="fa fa-caret-down"></i>
                  </a>
                  <ul class="nav nav-second-level">
                      {% for o in rubriken %}
                        <li>
                            <a href="{% url 'hofladen:hofladen-view' o.id%}"> 
                              {{ o.name }}
                            </a>
                        </li>
                      {% endfor %}
                  </ul>
              </li>
              <li>
                  <a href=#><i class="fa fa-eye fa-fw"></i>  
                      Artikel einer Rubrik
                      <i class="fa fa-caret-down"></i>
                  </a>
                  <ul class="nav nav-second-level">
                    {% for otype in unterrubriken %}
                        <li>
                            <a href="#"><i class="fa fa-eye fa-fw"></i>{{ otype.name }}
                                <span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                {% for artikel in otype.unterrubrik %}
                                    <li>
                                        <a href="{% url 'hofladen:hofladen-view' otype.id artikel.id %}">     {{ artikel.name }}
                                        </a>
                                    </li>
                                {% endfor %}
                            </ul>
                        </li>
                    {% endfor %}
                    </ul>
              </li>
              <li>
                  <a href="{% url 'hofladen:unverp-view' 1 %}"><b>unverpackte</b> Ware</a>
              </li>
            </ul>
        </div>
    </div>
  </nav>
</div>

    <div class="col-sm-9">
      <div class="main">      
        {% block content %}
        {% endblock content %}
      </div>
    </div>
</div>

<!-- Metis Menu Plugin JavaScript -->
<script src="{% static 'vendor/metisMenu/metisMenu.min.js' %}"></script>

<!-- Custom Theme JavaScript -->
    <script src="{% static 'js/sb-admin-2.js' %}"></script>

  <script src="{% static 'hofladen_map.js' %}"></script>

</body>
</html>